package hr.fer.zemris.java.raytracer;

import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.RecursiveAction;

import hr.fer.zemris.java.raytracer.model.GraphicalObject;
import hr.fer.zemris.java.raytracer.model.IRayTracerProducer;
import hr.fer.zemris.java.raytracer.model.IRayTracerResultObserver;
import hr.fer.zemris.java.raytracer.model.LightSource;
import hr.fer.zemris.java.raytracer.model.Point3D;
import hr.fer.zemris.java.raytracer.model.Ray;
import hr.fer.zemris.java.raytracer.model.RayIntersection;
import hr.fer.zemris.java.raytracer.model.RayIntersectionSphere;
import hr.fer.zemris.java.raytracer.model.Scene;
import hr.fer.zemris.java.raytracer.model.Sphere;
import hr.fer.zemris.java.raytracer.viewer.RayTracerViewer;

/**
 * This program renders a scene by using the ray-casting algorithm.
 * It uses parallelization to speed up the process.
 * 
 * @author Mihael Stočko
 *
 */
public class RayCasterParallel {

	/**
	 * Main method.
	 * 
	 * @param args Not used.
	 */
	public static void main(String[] args) {
		RayTracerViewer.show(getIRayTracerProducer(),
		new Point3D(10,0,0),
		new Point3D(0,0,0),
		new Point3D(0,0,10),
		20, 20);
	}

	/**
	 * This method returns a new RayTracerProducer. The producer is generated by filling three
	 * arrays (one for every color component) with values.
	 * @return A new RayTracerProducer
	 */
	private static IRayTracerProducer getIRayTracerProducer() {
		return new IRayTracerProducer() {
			/**
			 * This method fills the color arrays with values and sends them to an observer.
			 */
			@Override
			public void produce(Point3D eye, Point3D view, Point3D viewUp,
					double horizontal, double vertical, int width, int height,
					long requestNo, IRayTracerResultObserver observer) {
				System.out.println("Započinjem izračune...");
		
				short[] red = new short[width*height];
				short[] green = new short[width*height];
				short[] blue = new short[width*height];

				Point3D OG = view.sub(eye).normalize();
				Point3D VUV = viewUp.normalize();
				
				Point3D yAxis = VUV.sub(OG.scalarMultiply(OG.scalarProduct(VUV))).normalize();
				Point3D xAxis = OG.vectorProduct(yAxis).normalize();
				Point3D zAxis = yAxis.vectorProduct(xAxis);
				
				Point3D screenCorner = view.sub(xAxis.scalarMultiply(horizontal/2)).add(yAxis.scalarMultiply(vertical/2));
				
				System.out.println();
				System.out.println("Parametri koje je dobila metoda");
				System.out.println("===============================");
				System.out.println("eye: " + pointToString(eye));
				System.out.println("view: " + pointToString(view));
				System.out.println("viewUp: " + pointToString(viewUp));
				System.out.println("width: " + width);
				System.out.println("height: " + height);
				System.out.println("horizontal: " + horizontal);
				System.out.println("vertical: " + vertical);
				System.out.println();
				System.out.println("Izračunato:");
				System.out.println("===============================");
				System.out.println("X-vektor: " + pointToString(xAxis));
				System.out.println("Y-vektor: " + pointToString(yAxis));
				System.out.println("Z-vektor: " + pointToString(zAxis));
				System.out.println("Screen-corner: " + pointToString(screenCorner));
				System.out.println();
				Scene scene = RayTracerViewer.createPredefinedScene();
				
				ForkJoinPool pool = new ForkJoinPool();
				pool.invoke(new Job(height, width, screenCorner, xAxis, yAxis, horizontal, vertical, eye, scene, red, green, blue, 0, height-1));
				pool.shutdown();
				
				System.out.println("Izračuni gotovi...");
				observer.acceptResult(red, green, blue, requestNo);
				System.out.println("Dojava gotova...");
			}
		};
	}

	/**
	 * Takes a scene, a ray and an array and fills the array with rgb components of the
	 * intersection point of the ray and the closest object.
	 * 
	 * @param scene
	 * @param ray
	 * @param rgb
	 */
	protected static void tracer(Scene scene , Ray ray , short[] rgb) {
		rgb[0] = 0;
		rgb[1] = 0;
		rgb[2] = 0;
		
		RayIntersection closest = findClosestIntersection(scene, ray);
		
		if(closest==null) {
			return;
		}
		
		rgb[0] = 15;
		rgb[1] = 15;
		rgb[2] = 15;
	
		for(LightSource light : scene.getLights()) {
			Ray lightToIntersection = Ray.fromPoints(light.getPoint(), closest.getPoint());
			RayIntersection temp = findClosestIntersection(scene, lightToIntersection);
			if(temp != null && temp.getPoint().sub(light.getPoint()).norm() + 0.0001 < 
					closest.getPoint().sub(light.getPoint()).norm()) {
				continue;
			}
			
			Point3D closestToLigth = light.getPoint().sub(closest.getPoint()).normalize();
			double cosDif = closest.getNormal().scalarProduct(closestToLigth)/
					closest.getNormal().norm()/closestToLigth.norm();
			
			rgb[0] += light.getR()*closest.getKdr()*cosDif;
			rgb[1] += light.getG()*closest.getKdg()*cosDif;
			rgb[2] += light.getB()*closest.getKdb()*cosDif;
			
			
			Point3D closestToEye = ray.start.sub(closest.getPoint()).normalize();
			Point3D reflected = closestToLigth.sub(closest.getNormal().
					scalarMultiply(closestToLigth.scalarMultiply(2).scalarProduct(closest.getNormal())/closest.
							getNormal().norm()/closest.getNormal().norm()));
			
			double cosRefl = reflected.scalarProduct(closestToEye)/reflected.norm()/closestToEye.norm();
			
			rgb[0] += light.getR()*closest.getKrr()*Math.pow(cosRefl, closest.getKrn());
			rgb[1] += light.getG()*closest.getKrg()*Math.pow(cosRefl, closest.getKrn());
			rgb[2] += light.getB()*closest.getKrb()*Math.pow(cosRefl, closest.getKrn());
		}
	}
	
	/**
	 * Takes a point and returns its string representation.
	 * @param p Point
	 */
	private static String pointToString(Point3D p) {
		return "(" + p.x + ", " + p.y + ", " + p.z + ")";
	}
	
	/**
	 * For the given scene and ray, returns the closest intersection with an object.
	 * 
	 * @return the closest intersection with an object
	 */
	protected static RayIntersection findClosestIntersection(Scene scene, Ray ray) {
		RayIntersection intersection = null;
		for(GraphicalObject obj : scene.getObjects()) {
			if(obj instanceof Sphere) {
				RayIntersectionSphere newIntersection = (RayIntersectionSphere)obj.findClosestRayIntersection(ray);
				if(newIntersection == null || 
						intersection != null && intersection.getDistance() <= newIntersection.getDistance()) {
					continue;
				}
				newIntersection.setSphereCenter(((Sphere)obj).getCenter());
				intersection = newIntersection;
				
			}	
		}

		return intersection;
	}
	
	/**
	 * This class models a job for a single thread.
	 * 
	 * @author Mihael Stočko
	 *
	 */
	public static class Job extends RecursiveAction {
		private static final long serialVersionUID = 1L;
		
		/**
		 * Minimal height of the stripe to be filled.
		 */
		final int threshold = 16;
		
		/**
		 * Height of the screen
		 */
		int height;
		
		/**
		 * Width of the screen
		 */
		int width;
		
		/**
		 * Width of the projection pane
		 */
		double horizontal;
		
		/**
		 * Height of the projection pane
		 */
		double vertical;
		
		/**
		 * Corner of the projection pane
		 */
		Point3D screenCorner;
		
		/**
		 * Vector denoting the x-axis
		 */
		Point3D xAxis;
		
		/**
		 * Vector denoting the y-axis
		 */
		Point3D yAxis;
		
		/**
		 * Point that the observer is positioned at
		 */
		Point3D eye;
		
		/**
		 * Scene
		 */
		Scene scene;
		
		/**
		 * Red component for every pixel
		 */
		short[] red;
		
		/**
		 * Green component for every pixel
		 */
		short[] green;
		
		/**
		 * Blue component for every pixel
		 */
		short[] blue;
		
		/**
		 * Starting y for this thread
		 */
		int yMin;
		
		/**
		 * Ending y for this thread
		 */
		int yMax;
		
		/**
		 * Constructor
		 */
		public Job(int height, int width, Point3D screenCorner, Point3D xAxis, Point3D yAxis,
				double horizontal, double vertical, Point3D eye, Scene scene, short[] red,
				short[] green, short[] blue, int yMin, int yMax) {
			this.height = height;
			this.width = width;
			this.horizontal = horizontal;
			this.vertical = vertical;
			this.screenCorner = screenCorner;
			this.xAxis = xAxis;
			this.yAxis = yAxis;
			this.eye = eye;
			this.scene = scene;
			this.red = red;
			this.green = green;
			this.blue = blue;
			this.yMin = yMin;
			this.yMax = yMax;
		}
		
		/**
		 * Checks if the given stripe is wider than threshold. If it is, it splits this job into
		 * two jobs and. If it is not, then computeDirect is called.
		 */
		@Override
		protected void compute() {
			if(yMax - yMin + 1 <= threshold) {
				computeDirect();
				return;
			}
			invokeAll(
				new Job(height, width, screenCorner, xAxis, yAxis, horizontal, vertical, eye, scene, red, green, blue, yMin, yMin+(yMax-yMin)/2),
				new Job(height, width, screenCorner, xAxis, yAxis, horizontal, vertical, eye, scene, red, green, blue, yMin+(yMax-yMin)/2+1, yMax)
			);
		}
		
		/**
		 * Computes the r, g and b components for every point in the given stripe. 
		 */
		public void computeDirect() {
			short[] rgb = new short[3];
			int offset = yMin*width;
			
			for(int y = yMin; y <= yMax; y++) {
				for(int x = 0; x < width; x++) {
					Point3D screenPoint = screenCorner.add(xAxis.scalarMultiply(x*horizontal/(width-1)))
							.sub(yAxis.scalarMultiply(y*vertical/(height-1)));
					Ray ray = Ray.fromPoints(eye, screenPoint);
					tracer(scene, ray, rgb);
					red[offset] = rgb[0] > 255 ? 255 : rgb[0];
					green[offset] = rgb[1] > 255 ? 255 : rgb[1];
					blue[offset] = rgb[2] > 255 ? 255 : rgb[2];
					offset++;
				}
			}
		}
	}
}
